# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ceb9599775c4e7a13c4a1c218070b502bba4eb0f105bfc7751171b6d34e8520f25e8c1f2def2fcc245024c0ae58bf525db26b81402b65bc7b1e9291379dd3a0

test:
  secret_key_base: d0fc56408bacf6c9555aaab4de3b9edea84c61c5e13b5983ed7484c9d0fa899bcdbae69a4cd1ad5d5ec4791dfa76b45fe2b5b4ef6a10b18dcf6e66951fa6ed7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
